AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  heua-api: Backend Aplikasi Manajement Keuangan HeUa

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: nodejs22.x
    Tracing: Active
    Architectures:
     - arm64
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  HeuaAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth
      Handler: handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HeuaTable 
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  HeuaTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/transaction
      Handler: handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HeuaTable 
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  HeuaStatisticFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/statistic
      Handler: handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HeuaTable 
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  HeuaTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete #Retain
    UpdateReplacePolicy: Delete #Retain
    Properties:
      TableName: HeuaData
      BillingMode: PROVISIONED 
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
    

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  HeuaAuthFunctionUrl:
    Description: Auth Lambda Function URL
    Value: !GetAtt HeuaAuthFunctionUrl.FunctionUrl

  HeuaTransactionFunctionUrl:
    Description: Transaction Lambda Function URL
    Value: !GetAtt HeuaTransactionFunctionUrl.FunctionUrl

  HeuaStatisticFunctionUrl:
    Description: Statistic Lambda Function URL
    Value: !GetAtt HeuaStatisticFunctionUrl.FunctionUrl
